### ISSUE TITLE
Could not determine java version from '11.0.3'.

### ISSUE THREAD

**Issue by hemangchawla** [lessthanoptimal/PyBoof#3] opened 2019-07-25 09:27 UTC
On running ` ./setup.py build `, I get the following error:
```
 ./setup.py build 
running build
running build_py

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.3'.
```
Could you please suggest how to install PyBoof and resolve this issue?

**Comment by hemangchawla** [comment] 2019-07-25 10:49
This error is removed by changing the gradle properties using:
```
gedit gradle/wrapper/gradle-wrapper.properties 
```
The last line was replaced with:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.5.1-bin.zip
```

However, it gives another error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '<Workspace_Path>/PyBoof/build.gradle' line: 9

* What went wrong:
A problem occurred evaluating root project 'PyBoof'.
> Cannot add task 'wrapper' as a task with that name already exists.
```

**Comment by hemangchawla** [comment] 2019-07-25 11:00
The above issue is then fixed by modifying the build.gradle
```
gedit build.gradle
```
Replacing the `task wrapper`... with:
```
wrapper{
    gradleVersion = '5.5.1'
}
```

And then running the `./setup.py build`  returns:

```
running build
running build_py

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 8s
2 actionable tasks: 2 executed
creating build/lib
creating build/lib/pyboof
copying pyboof/flow.py -> build/lib/pyboof
copying pyboof/__init__.py -> build/lib/pyboof
copying pyboof/stereo.py -> build/lib/pyboof
copying pyboof/image.py -> build/lib/pyboof
copying pyboof/geo.py -> build/lib/pyboof
copying pyboof/common.py -> build/lib/pyboof
copying pyboof/calib.py -> build/lib/pyboof
copying pyboof/recognition.py -> build/lib/pyboof
copying pyboof/ip.py -> build/lib/pyboof
copying pyboof/sfm.py -> build/lib/pyboof
copying pyboof/feature.py -> build/lib/pyboof
copying pyboof/swing.py -> build/lib/pyboof
copying pyboof/PyBoof-all.jar -> build/lib/pyboof
copying pyboof/build_date.txt -> build/lib/pyboof
```

Hence the build is successful.

**Comment by lessthanoptimal** [comment] 2019-11-04 02:20
sorry for being so slow to fix this. I've not actually been able to reproduce it on my end. Hesitant to update the Gradle version since I standard on 4.10 across several projects.

The good news is that I'm adding a few new features and updating it for the latest stable BoofCV

**Comment by lessthanoptimal** [comment] 2020-06-15 02:28
Fixed in latest release

**Closed by lessthanoptimal** 2020-06-15 02:28 UTC
